"""added more technical indicators

Revision ID: 0a7b5dc3aded
Revises: 606a7b34df96
Create Date: 2026-08-01 14:12:32.583075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a7b5dc3aded'
down_revision = '606a7b34df96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('DayOfWeek', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('Month', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('Quarter', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('SMA100', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('SMA200', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('EMA50', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('EMA100', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('VolumeSMA20', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('VolumeRatio', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('Return5', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('Return10', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('Return20', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('GapPct', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('BBMiddle', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('BBStd', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('BBUpper', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('BBLower', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('BBWidth', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('BBPercentB', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('TrueRange', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('ATR14', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('ATRPct', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('OBV', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('OBVChange', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('StochasticK', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('StochasticD', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('WilliamsR', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('ROC10', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('Momentum10', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('CloseLag1', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('CloseLag2', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('CloseLag5', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('ReturnLag1', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('ReturnLag2', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('ReturnLag5', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('RSILag1', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('MACDLag1', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('VolumeLag1', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('RollingMean5', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('RollingMean10', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('RollingMean20', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('Volatility5', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('Volatility10', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('Volatility20', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('RollingHigh20', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('RollingLow20', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('DistanceFromHigh20', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('DistanceFromLow20', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('CloseToSMA20', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('CloseToSMA50', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('CloseToSMA200', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('SMA20ToSMA50', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('EMA12ToEMA26', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('DistanceFromSMA20', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('DistanceFromSMA50', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_data', schema=None) as batch_op:
        batch_op.drop_column('DistanceFromSMA50')
        batch_op.drop_column('DistanceFromSMA20')
        batch_op.drop_column('EMA12ToEMA26')
        batch_op.drop_column('SMA20ToSMA50')
        batch_op.drop_column('CloseToSMA200')
        batch_op.drop_column('CloseToSMA50')
        batch_op.drop_column('CloseToSMA20')
        batch_op.drop_column('DistanceFromLow20')
        batch_op.drop_column('DistanceFromHigh20')
        batch_op.drop_column('RollingLow20')
        batch_op.drop_column('RollingHigh20')
        batch_op.drop_column('Volatility20')
        batch_op.drop_column('Volatility10')
        batch_op.drop_column('Volatility5')
        batch_op.drop_column('RollingMean20')
        batch_op.drop_column('RollingMean10')
        batch_op.drop_column('RollingMean5')
        batch_op.drop_column('VolumeLag1')
        batch_op.drop_column('MACDLag1')
        batch_op.drop_column('RSILag1')
        batch_op.drop_column('ReturnLag5')
        batch_op.drop_column('ReturnLag2')
        batch_op.drop_column('ReturnLag1')
        batch_op.drop_column('CloseLag5')
        batch_op.drop_column('CloseLag2')
        batch_op.drop_column('CloseLag1')
        batch_op.drop_column('Momentum10')
        batch_op.drop_column('ROC10')
        batch_op.drop_column('WilliamsR')
        batch_op.drop_column('StochasticD')
        batch_op.drop_column('StochasticK')
        batch_op.drop_column('OBVChange')
        batch_op.drop_column('OBV')
        batch_op.drop_column('ATRPct')
        batch_op.drop_column('ATR14')
        batch_op.drop_column('TrueRange')
        batch_op.drop_column('BBPercentB')
        batch_op.drop_column('BBWidth')
        batch_op.drop_column('BBLower')
        batch_op.drop_column('BBUpper')
        batch_op.drop_column('BBStd')
        batch_op.drop_column('BBMiddle')
        batch_op.drop_column('GapPct')
        batch_op.drop_column('Return20')
        batch_op.drop_column('Return10')
        batch_op.drop_column('Return5')
        batch_op.drop_column('VolumeRatio')
        batch_op.drop_column('VolumeSMA20')
        batch_op.drop_column('EMA100')
        batch_op.drop_column('EMA50')
        batch_op.drop_column('SMA200')
        batch_op.drop_column('SMA100')
        batch_op.drop_column('Quarter')
        batch_op.drop_column('Month')
        batch_op.drop_column('DayOfWeek')

    # ### end Alembic commands ###
