"""Add ticker timestamp constraint

Revision ID: 606a7b34df96
Revises: c3fbba41e482
Create Date: 2026-08-01 04:54:37.992379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '606a7b34df96'
down_revision = 'c3fbba41e482'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_data', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_stock_ticker_timestamp', ['ticker', 'Timestamp'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_data', schema=None) as batch_op:
        batch_op.drop_constraint('uq_stock_ticker_timestamp', type_='unique')

    # ### end Alembic commands ###
