"""Create stock data table

Revision ID: c3fbba41e482
Revises: 
Create Date: 2026-08-01 04:30:19.997824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3fbba41e482'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Volume', sa.Float(), nullable=False),
    sa.Column('VWAP', sa.Float(), nullable=False),
    sa.Column('Open', sa.Float(), nullable=False),
    sa.Column('Close', sa.Float(), nullable=False),
    sa.Column('High', sa.Float(), nullable=False),
    sa.Column('Low', sa.Float(), nullable=False),
    sa.Column('Timestamp', sa.DateTime(), nullable=False),
    sa.Column('Trades', sa.Integer(), nullable=False),
    sa.Column('SMA20', sa.Float(), nullable=False),
    sa.Column('SMA50', sa.Float(), nullable=False),
    sa.Column('EMA12', sa.Float(), nullable=False),
    sa.Column('EMA26', sa.Float(), nullable=False),
    sa.Column('RSI', sa.Float(), nullable=False),
    sa.Column('MACD', sa.Float(), nullable=False),
    sa.Column('Signal', sa.Float(), nullable=False),
    sa.Column('Histogram', sa.Float(), nullable=False),
    sa.Column('Daily_Return', sa.Float(), nullable=False),
    sa.Column('High_Low_Percent', sa.Float(), nullable=False),
    sa.Column('Open_Close_Percent', sa.Float(), nullable=False),
    sa.Column('ticker', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_data')
    # ### end Alembic commands ###
